# Runs Earthly targets
name: Earthly Satellite
on: push
jobs:
    run-tests:
        runs-on: ubuntu-latest
        env:
            EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
            DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            FORCE_COLOR: 1
        steps:
            - uses: earthly/actions-setup@v1
              with:
                  version: v0.7.23
            - uses: actions/checkout@v2
            - name: Put back the git branch into git (Earthly uses it for tagging)
              run: |
                  branch=""
                  if [ -n "$GITHUB_HEAD_REF" ]; then
                    branch="$GITHUB_HEAD_REF"
                  else
                    branch="${GITHUB_REF##*/}"
                  fi
                  git checkout -b "$branch" || true
            - name: fetch submodule
              run: git submodule update --init --recursive --depth 1
            - name: Earthly version
              run: earthly --version
            - name: Test all on satellite
              run: earthly --auto-skip --no-output --strict --sat emaps-ci --org electricitymaps +prepare
